[project]
name = "uao-neumonia"
version = "0.1.0"
description = "Herramienta para la detección rápida de neumonía usando IA"
readme = "README.md"
requires-python = "==3.11.9"
dependencies = [
    "tensorflow==2.21.0",
    "keras==3.14.1",
    "numpy==2.4.4",
    "h5py==3.14.0",
    "opencv-python==4.13.0.92",
    "pydicom==3.0.2",
    "pillow==12.2.0",
    "tkcap==0.0.4",
    "click>=8.4.1",
    "pandas>=3.0.3",
    "fpdf>=1.7.2",
    "openpyxl>=3.1.5",
    "tqdm>=4.67.3",
    "tabulate>=0.10.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.14",
]

[tool.ruff]
# Evitamos analizar librerías del sistema en el entorno virtual
extend-exclude = [".venv", "__pycache__", "build", "dist"]

[tool.ruff.lint]
# E = Estilo PEP8, F = Errores lógicos, D = Validación de Docstrings
select = ["E", "F", "D"]

[tool.ruff.lint.pydocstyle]
# Aquí es donde se declara de forma correcta el estilo Google exigido
convention = "google"
